# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 01:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2015, 12, 14, 1, 19, 23, 99493, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
