# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20151215_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='content',
        ),
    ]
