# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 05:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20151215_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 15, 5, 51, 13, 427205, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 15, 5, 51, 17, 747207, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 15, 5, 51, 21, 107026, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 15, 5, 51, 27, 586665, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 15, 5, 51, 31, 738778, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 15, 5, 51, 37, 298523, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 15, 5, 51, 41, 882441, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 15, 5, 51, 47, 146631, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 15, 5, 51, 52, 498109, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 15, 5, 51, 55, 978419, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 15, 5, 51, 59, 898279, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 12, 15, 5, 52, 4, 42473, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
